import { createContext, useContext, useState, ReactNode } from 'react';

export type AdminLanguage = 'en' | 'ru' | 'lv';

interface AdminLanguageContextType {
  language: AdminLanguage;
  setLanguage: (lang: AdminLanguage) => void;
  t: (key: string) => string;
}

const AdminLanguageContext = createContext<AdminLanguageContextType | undefined>(undefined);

const adminTranslations: Record<AdminLanguage, Record<string, string>> = {
  en: {
    // Login
    'login.title': 'Admin Login',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.button': 'Sign In',
    'login.error': 'Invalid credentials',

    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.items': 'Items',
    'sidebar.cases': 'Cases',
    'sidebar.requests': 'Requests',
    'sidebar.problemQueue': 'Problem Queue',
    'sidebar.users': 'Users',
    'sidebar.logs': 'Logs / Audit',
    'sidebar.settings': 'Settings',

    // Topbar
    'topbar.search': 'Search users, requests...',
    'topbar.profile': 'Profile',
    'topbar.logout': 'Logout',
    'topbar.requests': 'Requests',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.casesOpened': 'Cases Opened',
    'dashboard.pendingRequests': 'Pending Requests',
    'dashboard.problemCases': 'Problem Cases',
    'dashboard.lowStock': 'Low Stock Items',
    'dashboard.today': 'Today',
    'dashboard.thisWeek': 'This Week',
    'dashboard.thisMonth': 'This Month',
    'dashboard.viewRequests': 'View Requests',
    'dashboard.viewLowStock': 'View Low Stock',
    'dashboard.viewProblems': 'View Problems',

    // Items
    'items.title': 'Items Management',
    'items.addNew': 'Add New Item',
    'items.search': 'Search items...',
    'items.filterAll': 'All Types',
    'items.filterPhysical': 'Physical',
    'items.filterBalance': 'Balance',
    'items.filterVirtual': 'Virtual',
    'items.name': 'Name',
    'items.type': 'Type',
    'items.rarity': 'Rarity',
    'items.stock': 'Stock',
    'items.status': 'Status',
    'items.lastModified': 'Last Modified',
    'items.active': 'Active',
    'items.hidden': 'Hidden',
    'items.edit': 'Edit',
    'items.delete': 'Delete',
    'items.typePhysical': 'Physical Item',
    'items.typeBalance': 'Balance Bonus',
    'items.typeVirtual': 'Virtual Item',
    'items.outOfStock': 'Out of Stock',
    'items.lowStock': 'Low Stock',

    // Item Form
    'itemForm.title': 'Item Details',
    'itemForm.create': 'Create Item',
    'itemForm.update': 'Update Item',
    'itemForm.nameLv': 'Name (LV)',
    'itemForm.nameRu': 'Name (RU)',
    'itemForm.nameEn': 'Name (EN)',
    'itemForm.descLv': 'Description (LV)',
    'itemForm.descRu': 'Description (RU)',
    'itemForm.descEn': 'Description (EN)',
    'itemForm.type': 'Item Type',
    'itemForm.rarity': 'Rarity',
    'itemForm.image': 'Card Image (PNG)',
    'itemForm.stock': 'Stock Quantity',
    'itemForm.amount': 'Balance Amount',
    'itemForm.isActive': 'Active',
    'itemForm.cancel': 'Cancel',
    'itemForm.save': 'Save Item',
    'itemForm.copyFrom': 'Copy from',
    'itemForm.preview': 'Preview',

    // Cases
    'cases.title': 'Cases Management',
    'cases.addNew': 'Add New Case',
    'cases.editCase': 'Edit Case',
    'cases.caseName': 'Case Name',
    'cases.image': 'Image',
    'cases.type': 'Type',
    'cases.typeDaily': 'Daily',
    'cases.typeMonthly': 'Monthly',
    'cases.typeEvent': 'Event',
    'cases.threshold': 'Threshold',
    'cases.eventDuration': 'Event Duration',
    'cases.status': 'Status',
    'cases.draft': 'Draft',
    'cases.published': 'Published',
    'cases.archived': 'Archived',
    'cases.lastModified': 'Last Modified',
    'cases.edit': 'Edit',
    'cases.delete': 'Delete',
    'cases.deleteConfirm': 'Are you sure you want to delete this case?',
    'cases.search': 'Search cases...',
    'cases.filterTypeAll': 'All Types',
    'cases.filterTypeDaily': 'Daily',
    'cases.filterTypeMonthly': 'Monthly',
    'cases.filterTypeEvent': 'Event',
    'cases.filterStatusAll': 'All Statuses',
    'cases.filterStatusDraft': 'Draft',
    'cases.filterStatusPublished': 'Published',
    'cases.filterStatusArchived': 'Archived',

    // Case Form
    'caseForm.title': 'Case Details',
    'caseForm.create': 'Create Case',
    'caseForm.update': 'Update Case',
    'caseForm.publish': 'Publish Case',
    'caseForm.nameLv': 'Name (LV)',
    'caseForm.nameRu': 'Name (RU)',
    'caseForm.nameEn': 'Name (EN)',
    'caseForm.image': 'Case Image (PNG)',
    'caseForm.type': 'Case Type',
    'caseForm.threshold': 'Deposit Threshold ($)',
    'caseForm.items': 'Case Items',
    'caseForm.addItem': 'Add Item',
    'caseForm.removeItem': 'Remove',
    'caseForm.item': 'Item',
    'caseForm.chance': 'Chance (%)',
    'caseForm.weight': 'Weight',
    'caseForm.modePercent': 'Percent Mode',
    'caseForm.modeWeight': 'Weight Mode',
    'caseForm.autoCalculate': 'Auto Calculate',
    'caseForm.totalChance': 'Total',
    'caseForm.warningTotal': 'Total must equal 100%',
    'caseForm.saveDraft': 'Save as Draft',
    'caseForm.cancel': 'Cancel',

    // Requests
    'requests.title': 'Claim Requests',
    'requests.search': 'Search by phone, nickname, uuid...',
    'requests.filterAll': 'All Statuses',
    'requests.filterPending': 'Pending',
    'requests.filterApproved': 'Approved',
    'requests.filterDenied': 'Denied',
    'requests.filterReturned': 'Returned',
    'requests.filterExpired': 'Expired',
    'requests.requestId': 'Request ID',
    'requests.user': 'User',
    'requests.item': 'Item',
    'requests.case': 'Case',
    'requests.pc': 'PC',
    'requests.date': 'Date',
    'requests.status': 'Status',
    'requests.actions': 'Actions',
    'requests.approve': 'Approve',
    'requests.deny': 'Deny',
    'requests.return': 'Return to Stock',
    'requests.view': 'View',
    'requests.pending': 'Pending',
    'requests.approved': 'Approved',
    'requests.denied': 'Denied',
    'requests.returned': 'Returned',
    'requests.expired': 'Expired',

    // Request Details Modal
    'requestModal.title': 'Request Details',
    'requestModal.requestId': 'Request ID',
    'requestModal.user': 'User',
    'requestModal.phone': 'Phone',
    'requestModal.item': 'Item',
    'requestModal.case': 'Case',
    'requestModal.pc': 'PC',
    'requestModal.date': 'Request Date',
    'requestModal.status': 'Status',
    'requestModal.comment': 'Comment / Reason',
    'requestModal.commentPlaceholder': 'Enter comment...',
    'requestModal.approve': 'Approve Request',
    'requestModal.deny': 'Deny Request',
    'requestModal.return': 'Return to Stock',
    'requestModal.close': 'Close',
    'requestModal.confirmApprove': 'Confirm approval?',
    'requestModal.confirmDeny': 'Confirm denial?',
    'requestModal.confirmReturn': 'Return item to stock?',

    // Problem Queue
    'problems.title': 'Problem Queue',
    'problems.search': 'Search problems...',
    'problems.filterAll': 'All Types',
    'problems.filterError': 'Delivery Error',
    'problems.filterExpired': 'Expired',
    'problems.filterFailed': 'Failed Payment',
    'problems.requestId': 'Request ID',
    'problems.user': 'User',
    'problems.issue': 'Issue',
    'problems.date': 'Date',
    'problems.actions': 'Actions',
    'problems.retry': 'Retry',
    'problems.return': 'Return to Stock',
    'problems.resolve': 'Mark Resolved',
    'problems.comment': 'Add Comment',

    // Users
    'users.title': 'Users Management',
    'users.addNew': 'Add New User',
    'users.editUser': 'Edit User',
    'users.username': 'Username',
    'users.email': 'Email',
    'users.fullName': 'Full Name',
    'users.password': 'Password',
    'users.role': 'Role',
    'users.permissions': 'Permissions',
    'users.customPermissions': 'Custom Permissions',
    'users.useCustomPermissions': 'Use custom permissions instead of role defaults',
    'users.roleOwner': 'Owner',
    'users.roleAdmin': 'Administrator',
    'users.roleModerator': 'Moderator',
    'users.lastActive': 'Last Active',
    'users.createdAt': 'Created',
    'users.status': 'Status',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.deleteConfirm': 'Are you sure you want to delete this user? This action cannot be undone.',
    
    // Permissions
    'permissions.viewDashboard': 'View Dashboard',
    'permissions.viewCases': 'View Cases',
    'permissions.createCase': 'Create Cases',
    'permissions.editCase': 'Edit Cases',
    'permissions.deleteCase': 'Delete Cases',
    'permissions.viewPrizes': 'View Prizes',
    'permissions.createPrize': 'Create Prizes',
    'permissions.editPrize': 'Edit Prizes',
    'permissions.deletePrize': 'Delete Prizes',
    'permissions.viewClaims': 'View Claims',
    'permissions.manageClaims': 'Manage Claims',
    'permissions.viewUsers': 'View Users',
    'permissions.manageUsers': 'Manage Users',
    'permissions.viewLogs': 'View Logs',
    'permissions.viewSettings': 'View Settings',
    'permissions.manageSettings': 'Manage Settings',

    // User Profile Modal
    'userModal.title': 'User Profile',
    'userModal.info': 'User Information',
    'userModal.nickname': 'Nickname',
    'userModal.phone': 'Phone',
    'userModal.uuid': 'UUID',
    'userModal.joined': 'Member Since',
    'userModal.history': 'Opening History',
    'userModal.inventory': 'User Inventory',
    'userModal.item': 'Item',
    'userModal.case': 'Case',
    'userModal.date': 'Date',
    'userModal.status': 'Status',
    'userModal.markDelivered': 'Mark as Delivered',
    'userModal.retryDelivery': 'Retry Delivery',
    'userModal.returnStock': 'Return to Stock',
    'userModal.close': 'Close',

    // Logs
    'logs.title': 'Activity Logs',
    'logs.clientActivity': 'Client Activity',
    'logs.adminActivity': 'Admin Activity',
    'logs.player': 'Player',
    'logs.case': 'Case',
    'logs.prize': 'Prize',
    'logs.rarity': 'Rarity',
    'logs.value': 'Value',
    'logs.timestamp': 'Time',
    'logs.admin': 'Admin',
    'logs.action': 'Action',
    'logs.target': 'Target',
    'logs.details': 'Details',
    'logs.ipAddress': 'IP Address',
    'logs.sortBy': 'Sort by',
    'logs.sortOrder': 'Order',
    'logs.ascending': 'Ascending',
    'logs.descending': 'Descending',
    'logs.sortByDate': 'Date',
    'logs.sortByValue': 'Value',
    'logs.sortByRarity': 'Rarity',
    'logs.sortByPrize': 'Prize',
    'logs.sortByAction': 'Action',
    'logs.sortByAdmin': 'Admin',
    'logs.filterByRarity': 'Filter by Rarity',
    'logs.filterByAction': 'Filter by Action',
    'logs.allRarities': 'All Rarities',
    'logs.allActions': 'All Actions',
    
    // Admin Actions
    'actions.login': 'Login',
    'actions.logout': 'Logout',
    'actions.caseCreated': 'Created Case',
    'actions.caseEdited': 'Edited Case',
    'actions.caseDeleted': 'Deleted Case',
    'actions.prizeCreated': 'Created Prize',
    'actions.prizeEdited': 'Edited Prize',
    'actions.prizeDeleted': 'Deleted Prize',
    'actions.claimApproved': 'Approved Claim',
    'actions.claimRejected': 'Rejected Claim',
    'actions.claimPending': 'Marked Claim as Pending',
    'actions.userCreated': 'Created User',
    'actions.userEdited': 'Edited User',
    'actions.userDeleted': 'Deleted User',
    'actions.settingsChanged': 'Changed Settings',

    // Settings
    'settings.title': 'Settings',
    'settings.save': 'Save Changes',
    'settings.general': 'General Settings',
    'settings.appearance': 'Appearance Settings',
    'settings.siteLogo': 'Site Logo URL',
    'settings.siteLogoHint': 'URL of the logo displayed in the application',
    'settings.bannerBackground': 'Event Banner Background',
    'settings.bannerBackgroundHint': 'Background image for seasonal/event banner section',
    'settings.profileBackground': 'Profile Background',
    'settings.profileBackgroundHint': 'Background image for player profile header',
    'settings.snowEffect': 'Snow Effect',
    'settings.snowEffectHint': 'Enable or disable falling snow animation on the site',
    'settings.maintenanceMode': 'Maintenance Mode',
    'settings.maintenanceModeHint': 'Block all users from accessing the application during maintenance',
    'settings.enabled': 'Enabled',
    'settings.disabled': 'Disabled',
    'settings.lowStockThreshold': 'Low Stock Threshold',
    'settings.expireTtl': 'Prize Expiration (Hours)',
    'settings.rarities': 'Rarity Settings',
    'settings.presets': 'Rarity Presets',

    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    'common.actions': 'Actions',
  },

  ru: {
    // Login
    'login.title': 'Вход в админку',
    'login.username': 'Имя пользователя',
    'login.password': 'Пароль',
    'login.button': 'Войти',
    'login.error': 'Неверные данные',

    // Sidebar
    'sidebar.dashboard': 'Панель управления',
    'sidebar.items': 'Призы',
    'sidebar.cases': 'Кейсы',
    'sidebar.requests': 'Заявки',
    'sidebar.problemQueue': 'Проблемные',
    'sidebar.users': 'Пользователи',
    'sidebar.logs': 'Логи / Аудит',
    'sidebar.settings': 'Настройки',

    // Topbar
    'topbar.search': 'Поиск пользователей, заявок...',
    'topbar.profile': 'Профиль',
    'topbar.logout': 'Выход',
    'topbar.requests': 'Заявки',

    // Dashboard
    'dashboard.title': 'Панель управления',
    'dashboard.casesOpened': 'Кейсов открыто',
    'dashboard.pendingRequests': 'Заявок в ожидании',
    'dashboard.problemCases': 'Проблемных случаев',
    'dashboard.lowStock': 'Мало на складе',
    'dashboard.today': 'Сегодня',
    'dashboard.thisWeek': 'На этой неделе',
    'dashboard.thisMonth': 'В этом месяце',
    'dashboard.viewRequests': 'Смотреть заявки',
    'dashboard.viewLowStock': 'Смотреть склад',
    'dashboard.viewProblems': 'Смотреть проблемы',

    // Items
    'items.title': 'Управление призами',
    'items.addNew': 'Добавить приз',
    'items.search': 'Поиск призов...',
    'items.filterAll': 'Все типы',
    'items.filterPhysical': 'Физические',
    'items.filterBalance': 'Баланс',
    'items.filterVirtual': 'Виртуальные',
    'items.name': 'Название',
    'items.type': 'Тип',
    'items.rarity': 'Редкость',
    'items.stock': 'Остаток',
    'items.status': 'Статус',
    'items.lastModified': 'Изменено',
    'items.active': 'Активен',
    'items.hidden': 'Скрыт',
    'items.edit': 'Редактировать',
    'items.delete': 'Удалить',
    'items.typePhysical': 'Физический предмет',
    'items.typeBalance': 'Бонус баланса',
    'items.typeVirtual': 'Виртуальный предмет',
    'items.outOfStock': 'Нет в наличии',
    'items.lowStock': 'Мало на складе',

    // Item Form
    'itemForm.title': 'Данные приза',
    'itemForm.create': 'Создать приз',
    'itemForm.update': 'Обновить приз',
    'itemForm.nameLv': 'Название (LV)',
    'itemForm.nameRu': 'Название (RU)',
    'itemForm.nameEn': 'Название (EN)',
    'itemForm.descLv': 'Описание (LV)',
    'itemForm.descRu': 'Описание (RU)',
    'itemForm.descEn': 'Описание (EN)',
    'itemForm.type': 'Тип приза',
    'itemForm.rarity': 'Редкость',
    'itemForm.image': 'Изображение карточки (PNG)',
    'itemForm.stock': 'Количество',
    'itemForm.amount': 'Сумма баланса',
    'itemForm.isActive': 'Активен',
    'itemForm.cancel': 'Отмена',
    'itemForm.save': 'Сохранить приз',
    'itemForm.copyFrom': 'Скопировать из',
    'itemForm.preview': 'Превью',

    // Cases
    'cases.title': 'Cases Management',
    'cases.addNew': 'Add New Case',
    'cases.editCase': 'Edit Case',
    'cases.caseName': 'Case Name',
    'cases.image': 'Image',
    'cases.type': 'Type',
    'cases.typeDaily': 'Daily',
    'cases.typeMonthly': 'Monthly',
    'cases.typeEvent': 'Event',
    'cases.threshold': 'Threshold',
    'cases.eventDuration': 'Event Duration',
    'cases.status': 'Status',
    'cases.draft': 'Draft',
    'cases.published': 'Published',
    'cases.archived': 'Archived',
    'cases.lastModified': 'Last Modified',
    'cases.edit': 'Edit',
    'cases.delete': 'Delete',
    'cases.deleteConfirm': 'Are you sure you want to delete this case?',
    'cases.search': 'Search cases...',
    'cases.filterTypeAll': 'All Types',
    'cases.filterTypeDaily': 'Daily',
    'cases.filterTypeMonthly': 'Monthly',
    'cases.filterTypeEvent': 'Event',
    'cases.filterStatusAll': 'All Statuses',
    'cases.filterStatusDraft': 'Draft',
    'cases.filterStatusPublished': 'Published',
    'cases.filterStatusArchived': 'Archived',

    // Case Form
    'caseForm.title': 'Данные кейса',
    'caseForm.create': 'Создать кейс',
    'caseForm.update': 'Обновить кейс',
    'caseForm.publish': 'Опубликовать кейс',
    'caseForm.nameLv': 'Название (LV)',
    'caseForm.nameRu': 'Название (RU)',
    'caseForm.nameEn': 'Название (EN)',
    'caseForm.image': 'Изображение кейса (PNG)',
    'caseForm.type': 'Тип кейса',
    'caseForm.threshold': 'Порог пополнения ($)',
    'caseForm.items': 'Содержимое кейса',
    'caseForm.addItem': 'Добавить предмет',
    'caseForm.removeItem': 'Удалить',
    'caseForm.item': 'Предмет',
    'caseForm.chance': 'Шанс (%)',
    'caseForm.weight': 'Вес',
    'caseForm.modePercent': 'Режим процентов',
    'caseForm.modeWeight': 'Режим весов',
    'caseForm.autoCalculate': 'Авторасчёт',
    'caseForm.totalChance': 'Итого',
    'caseForm.warningTotal': 'Сумма должна быть 100%',
    'caseForm.saveDraft': 'Сохранить черновик',
    'caseForm.cancel': 'Отмена',

    // Requests
    'requests.title': 'Заявки на получение',
    'requests.search': 'Поиск по телефону, никнейму, uuid...',
    'requests.filterAll': 'Все статусы',
    'requests.filterPending': 'В ожидании',
    'requests.filterApproved': 'Одобрено',
    'requests.filterDenied': 'Отклонено',
    'requests.filterReturned': 'Возвращено',
    'requests.filterExpired': 'Просрочено',
    'requests.requestId': 'ID заявки',
    'requests.user': 'Пользователь',
    'requests.item': 'Приз',
    'requests.case': 'Кейс',
    'requests.pc': 'ПК',
    'requests.date': 'Дата',
    'requests.status': 'Статус',
    'requests.actions': 'Действия',
    'requests.approve': 'Одобрить',
    'requests.deny': 'Отклонить',
    'requests.return': 'Вернуть на склад',
    'requests.view': 'Просмотр',
    'requests.pending': 'В ожидании',
    'requests.approved': 'Одобрено',
    'requests.denied': 'Отклонено',
    'requests.returned': 'Возвращено',
    'requests.expired': 'Просрочено',

    // Request Details Modal
    'requestModal.title': 'Детали заявки',
    'requestModal.requestId': 'ID заявки',
    'requestModal.user': 'Пользователь',
    'requestModal.phone': 'Телефон',
    'requestModal.item': 'Приз',
    'requestModal.case': 'Кейс',
    'requestModal.pc': 'ПК',
    'requestModal.date': 'Дата заявки',
    'requestModal.status': 'Статус',
    'requestModal.comment': 'Комментарий / Причина',
    'requestModal.commentPlaceholder': 'Введите комментарий...',
    'requestModal.approve': 'Одобрить заявку',
    'requestModal.deny': 'Отклонить заявку',
    'requestModal.return': 'Вернуть на склад',
    'requestModal.close': 'Закрыть',
    'requestModal.confirmApprove': 'Подтвердить одобрение?',
    'requestModal.confirmDeny': 'Подтвердить отклонение?',
    'requestModal.confirmReturn': 'Вернуть предмет на склад?',

    // Problem Queue
    'problems.title': 'Проблемные случаи',
    'problems.search': 'Поиск проблем...',
    'problems.filterAll': 'Все типы',
    'problems.filterError': 'Ошибка выдачи',
    'problems.filterExpired': 'Просрочено',
    'problems.filterFailed': 'Ошибка оплаты',
    'problems.requestId': 'ID заявки',
    'problems.user': 'Пользователь',
    'problems.issue': 'Проблема',
    'problems.date': 'Дата',
    'problems.actions': 'Действия',
    'problems.retry': 'Повторить',
    'problems.return': 'Вернуть на склад',
    'problems.resolve': 'Решено',
    'problems.comment': 'Добавить комментарий',

    // Users
    'users.title': 'Users Management',
    'users.addNew': 'Add New User',
    'users.editUser': 'Edit User',
    'users.username': 'Username',
    'users.email': 'Email',
    'users.fullName': 'Full Name',
    'users.password': 'Password',
    'users.role': 'Role',
    'users.permissions': 'Permissions',
    'users.customPermissions': 'Custom Permissions',
    'users.useCustomPermissions': 'Use custom permissions instead of role defaults',
    'users.roleOwner': 'Owner',
    'users.roleAdmin': 'Administrator',
    'users.roleModerator': 'Moderator',
    'users.lastActive': 'Last Active',
    'users.createdAt': 'Created',
    'users.status': 'Status',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.deleteConfirm': 'Are you sure you want to delete this user? This action cannot be undone.',
    
    // Permissions
    'permissions.viewDashboard': 'View Dashboard',
    'permissions.viewCases': 'View Cases',
    'permissions.createCase': 'Create Cases',
    'permissions.editCase': 'Edit Cases',
    'permissions.deleteCase': 'Delete Cases',
    'permissions.viewPrizes': 'View Prizes',
    'permissions.createPrize': 'Create Prizes',
    'permissions.editPrize': 'Edit Prizes',
    'permissions.deletePrize': 'Delete Prizes',
    'permissions.viewClaims': 'View Claims',
    'permissions.manageClaims': 'Manage Claims',
    'permissions.viewUsers': 'View Users',
    'permissions.manageUsers': 'Manage Users',
    'permissions.viewLogs': 'View Logs',
    'permissions.viewSettings': 'View Settings',
    'permissions.manageSettings': 'Manage Settings',

    // User Profile Modal
    'userModal.title': 'Профиль пользователя',
    'userModal.info': 'Информация',
    'userModal.nickname': 'Никнейм',
    'userModal.phone': 'Телефон',
    'userModal.uuid': 'UUID',
    'userModal.joined': 'Участник с',
    'userModal.history': 'История открытий',
    'userModal.inventory': 'Инвентарь пользователя',
    'userModal.item': 'Предмет',
    'userModal.case': 'Кейс',
    'userModal.date': 'Дата',
    'userModal.status': 'Статус',
    'userModal.markDelivered': 'Отметить выданным',
    'userModal.retryDelivery': 'Повторить выдачу',
    'userModal.returnStock': 'Вернуть на склад',
    'userModal.close': 'Закрыть',

    // Logs
    'logs.title': 'Activity Logs',
    'logs.clientActivity': 'Client Activity',
    'logs.adminActivity': 'Admin Activity',
    'logs.player': 'Player',
    'logs.case': 'Case',
    'logs.prize': 'Prize',
    'logs.rarity': 'Rarity',
    'logs.value': 'Value',
    'logs.timestamp': 'Time',
    'logs.admin': 'Admin',
    'logs.action': 'Action',
    'logs.target': 'Target',
    'logs.details': 'Details',
    'logs.ipAddress': 'IP Address',
    'logs.sortBy': 'Sort by',
    'logs.sortOrder': 'Order',
    'logs.ascending': 'Ascending',
    'logs.descending': 'Descending',
    'logs.sortByDate': 'Date',
    'logs.sortByValue': 'Value',
    'logs.sortByRarity': 'Rarity',
    'logs.sortByPrize': 'Prize',
    'logs.sortByAction': 'Action',
    'logs.sortByAdmin': 'Admin',
    'logs.filterByRarity': 'Filter by Rarity',
    'logs.filterByAction': 'Filter by Action',
    'logs.allRarities': 'All Rarities',
    'logs.allActions': 'All Actions',
    
    // Admin Actions
    'actions.login': 'Login',
    'actions.logout': 'Logout',
    'actions.caseCreated': 'Created Case',
    'actions.caseEdited': 'Edited Case',
    'actions.caseDeleted': 'Deleted Case',
    'actions.prizeCreated': 'Created Prize',
    'actions.prizeEdited': 'Edited Prize',
    'actions.prizeDeleted': 'Deleted Prize',
    'actions.claimApproved': 'Approved Claim',
    'actions.claimRejected': 'Rejected Claim',
    'actions.claimPending': 'Marked Claim as Pending',
    'actions.userCreated': 'Created User',
    'actions.userEdited': 'Edited User',
    'actions.userDeleted': 'Deleted User',
    'actions.settingsChanged': 'Changed Settings',

    // Settings
    'settings.title': 'Settings',
    'settings.save': 'Save Changes',
    'settings.general': 'General Settings',
    'settings.appearance': 'Appearance Settings',
    'settings.siteLogo': 'Site Logo URL',
    'settings.siteLogoHint': 'URL of the logo displayed in the application',
    'settings.bannerBackground': 'Event Banner Background',
    'settings.bannerBackgroundHint': 'Background image for seasonal/event banner section',
    'settings.profileBackground': 'Profile Background',
    'settings.profileBackgroundHint': 'Background image for player profile header',
    'settings.snowEffect': 'Snow Effect',
    'settings.snowEffectHint': 'Enable or disable falling snow animation on the site',
    'settings.maintenanceMode': 'Maintenance Mode',
    'settings.maintenanceModeHint': 'Block all users from accessing the application during maintenance',
    'settings.enabled': 'Enabled',
    'settings.disabled': 'Disabled',
    'settings.lowStockThreshold': 'Low Stock Threshold',
    'settings.expireTtl': 'Prize Expiration (Hours)',
    'settings.rarities': 'Rarity Settings',
    'settings.presets': 'Rarity Presets',

    // Common
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.view': 'Просмотр',
    'common.close': 'Закрыть',
    'common.confirm': 'Подтвердить',
    'common.success': 'Успешно',
    'common.error': 'Ошибка',
    'common.loading': 'Загрузка...',
    'common.noData': 'Нет данных',
    'common.actions': 'Действия',
  },

  lv: {
    // Login
    'login.title': 'Admina pierakstīšanās',
    'login.username': 'Lietotājvārds',
    'login.password': 'Parole',
    'login.button': 'Pieteikties',
    'login.error': 'Nepareizi dati',

    // Sidebar
    'sidebar.dashboard': 'Pārvaldības panelis',
    'sidebar.items': 'Prēmijas',
    'sidebar.cases': 'Kastes',
    'sidebar.requests': 'Pieteikumi',
    'sidebar.problemQueue': 'Problēmas',
    'sidebar.users': 'Lietotāji',
    'sidebar.logs': 'Žurnāli / Audits',
    'sidebar.settings': 'Iestatījumi',

    // Topbar
    'topbar.search': 'Meklēt lietotājus, pieteikumus...',
    'topbar.profile': 'Profils',
    'topbar.logout': 'Iziet',
    'topbar.requests': 'Pieteikumi',

    // Dashboard
    'dashboard.title': 'Pārvaldības panelis',
    'dashboard.casesOpened': 'Atvrtas kastes',
    'dashboard.pendingRequests': 'Gaida pieteikumi',
    'dashboard.problemCases': 'Problēmu gadījumi',
    'dashboard.lowStock': 'Zems krājums',
    'dashboard.today': 'Šodien',
    'dashboard.thisWeek': 'Šonedēļ',
    'dashboard.thisMonth': 'Šomēnes',
    'dashboard.viewRequests': 'Skatīt pieteikumus',
    'dashboard.viewLowStock': 'Skatīt krājumu',
    'dashboard.viewProblems': 'Skatīt problēmas',

    // Items
    'items.title': 'Prēmiju pārvaldība',
    'items.addNew': 'Pievienot prēmiju',
    'items.search': 'Meklēt prēmijas...',
    'items.filterAll': 'Visi tipi',
    'items.filterPhysical': 'Fiziski',
    'items.filterBalance': 'Bilance',
    'items.filterVirtual': 'Virtuāli',
    'items.name': 'Nosaukums',
    'items.type': 'Tips',
    'items.rarity': 'Retums',
    'items.stock': 'Krājums',
    'items.status': 'Statuss',
    'items.lastModified': 'Mainīts',
    'items.active': 'Aktīvs',
    'items.hidden': 'Paslēpts',
    'items.edit': 'Rediģēt',
    'items.delete': 'Dzēst',
    'items.typePhysical': 'Fizisks priekšmets',
    'items.typeBalance': 'Bilances bonuss',
    'items.typeVirtual': 'Virtuāls priekšmets',
    'items.outOfStock': 'Nav noliktavā',
    'items.lowStock': 'Zems krājums',

    // Item Form
    'itemForm.title': 'Prēmijas dati',
    'itemForm.create': 'Izveidot prēmiju',
    'itemForm.update': 'Atjaunināt prēmiju',
    'itemForm.nameLv': 'Nosaukums (LV)',
    'itemForm.nameRu': 'Nosaukums (RU)',
    'itemForm.nameEn': 'Nosaukums (EN)',
    'itemForm.descLv': 'Apraksts (LV)',
    'itemForm.descRu': 'Apraksts (RU)',
    'itemForm.descEn': 'Apraksts (EN)',
    'itemForm.type': 'Prēmijas tips',
    'itemForm.rarity': 'Retums',
    'itemForm.image': 'Kartes attēls (PNG)',
    'itemForm.stock': 'Daudzums',
    'itemForm.amount': 'Bilances summa',
    'itemForm.isActive': 'Aktīvs',
    'itemForm.cancel': 'Atcelt',
    'itemForm.save': 'Saglabāt prēmiju',
    'itemForm.copyFrom': 'Kopēt no',
    'itemForm.preview': 'Priekšskatījums',

    // Cases
    'cases.title': 'Cases Management',
    'cases.addNew': 'Add New Case',
    'cases.editCase': 'Edit Case',
    'cases.caseName': 'Case Name',
    'cases.image': 'Image',
    'cases.type': 'Type',
    'cases.typeDaily': 'Daily',
    'cases.typeMonthly': 'Monthly',
    'cases.typeEvent': 'Event',
    'cases.threshold': 'Threshold',
    'cases.eventDuration': 'Event Duration',
    'cases.status': 'Status',
    'cases.draft': 'Draft',
    'cases.published': 'Published',
    'cases.archived': 'Archived',
    'cases.lastModified': 'Last Modified',
    'cases.edit': 'Edit',
    'cases.delete': 'Delete',
    'cases.deleteConfirm': 'Are you sure you want to delete this case?',
    'cases.search': 'Search cases...',
    'cases.filterTypeAll': 'All Types',
    'cases.filterTypeDaily': 'Daily',
    'cases.filterTypeMonthly': 'Monthly',
    'cases.filterTypeEvent': 'Event',
    'cases.filterStatusAll': 'All Statuses',
    'cases.filterStatusDraft': 'Draft',
    'cases.filterStatusPublished': 'Published',
    'cases.filterStatusArchived': 'Archived',

    // Case Form
    'caseForm.title': 'Kastes dati',
    'caseForm.create': 'Izveidot kasti',
    'caseForm.update': 'Atjaunināt kasti',
    'caseForm.publish': 'Publicēt kasti',
    'caseForm.nameLv': 'Nosaukums (LV)',
    'caseForm.nameRu': 'Nosaukums (RU)',
    'caseForm.nameEn': 'Nosaukums (EN)',
    'caseForm.image': 'Kastes attēls (PNG)',
    'caseForm.type': 'Kastes tips',
    'caseForm.threshold': 'Papildināšanas slieksnis ($)',
    'caseForm.items': 'Kastes saturs',
    'caseForm.addItem': 'Pievienot priekšmetu',
    'caseForm.removeItem': 'Noņemt',
    'caseForm.item': 'Priekšmets',
    'caseForm.chance': 'Iespēja (%)',
    'caseForm.weight': 'Svars',
    'caseForm.modePercent': 'Procentu režīms',
    'caseForm.modeWeight': 'Svaru režīms',
    'caseForm.autoCalculate': 'Automātiskais aprēķins',
    'caseForm.totalChance': 'Kopā',
    'caseForm.warningTotal': 'Summai jābūt 100%',
    'caseForm.saveDraft': 'Saglabāt melnrakstu',
    'caseForm.cancel': 'Atcelt',

    // Requests
    'requests.title': 'Saņemšanas pieteikumi',
    'requests.search': 'Meklēt pēc tālruņa, segvārda, uuid...',
    'requests.filterAll': 'Visi statusi',
    'requests.filterPending': 'Gaida',
    'requests.filterApproved': 'Apstiprināts',
    'requests.filterDenied': 'Noraidīts',
    'requests.filterReturned': 'Atgriezts',
    'requests.filterExpired': 'Beidzies',
    'requests.requestId': 'Pieteikuma ID',
    'requests.user': 'Lietotājs',
    'requests.item': 'Prēmija',
    'requests.case': 'Kaste',
    'requests.pc': 'Dators',
    'requests.date': 'Datums',
    'requests.status': 'Statuss',
    'requests.actions': 'Darbības',
    'requests.approve': 'Apstiprināt',
    'requests.deny': 'Noraidīt',
    'requests.return': 'Atgriezt noliktavā',
    'requests.view': 'Skatīt',
    'requests.pending': 'Gaida',
    'requests.approved': 'Apstiprināts',
    'requests.denied': 'Noraidīts',
    'requests.returned': 'Atgriezts',
    'requests.expired': 'Beidzies',

    // Request Details Modal
    'requestModal.title': 'Pieteikuma detaļas',
    'requestModal.requestId': 'Pieteikuma ID',
    'requestModal.user': 'Lietotājs',
    'requestModal.phone': 'Tālrunis',
    'requestModal.item': 'Prēmija',
    'requestModal.case': 'Kaste',
    'requestModal.pc': 'Dators',
    'requestModal.date': 'Pieteikuma datums',
    'requestModal.status': 'Statuss',
    'requestModal.comment': 'Komentārs / Iemesls',
    'requestModal.commentPlaceholder': 'Ievadīt komentāru...',
    'requestModal.approve': 'Apstiprināt pieteikumu',
    'requestModal.deny': 'Noraidīt pieteikumu',
    'requestModal.return': 'Atgriezt noliktavā',
    'requestModal.close': 'Aizvērt',
    'requestModal.confirmApprove': 'Apstiprināt apstiprināšanu?',
    'requestModal.confirmDeny': 'Apstiprināt noraidīšanu?',
    'requestModal.confirmReturn': 'Atgriezt priekšmetu noliktavā?',

    // Problem Queue
    'problems.title': 'Problēmu gadījumi',
    'problems.search': 'Meklēt problēmas...',
    'problems.filterAll': 'Visi tipi',
    'problems.filterError': 'Piegādes kļūda',
    'problems.filterExpired': 'Beidzies',
    'problems.filterFailed': 'Maksājuma kļūda',
    'problems.requestId': 'Pieteikuma ID',
    'problems.user': 'Lietotājs',
    'problems.issue': 'Problēma',
    'problems.date': 'Datums',
    'problems.actions': 'Darbības',
    'problems.retry': 'Mēģināt vēlreiz',
    'problems.return': 'Atgriezt noliktavā',
    'problems.resolve': 'Atrisināts',
    'problems.comment': 'Pievienot komentāru',

    // Users
    'users.title': 'Users Management',
    'users.addNew': 'Add New User',
    'users.editUser': 'Edit User',
    'users.username': 'Username',
    'users.email': 'Email',
    'users.fullName': 'Full Name',
    'users.password': 'Password',
    'users.role': 'Role',
    'users.permissions': 'Permissions',
    'users.customPermissions': 'Custom Permissions',
    'users.useCustomPermissions': 'Use custom permissions instead of role defaults',
    'users.roleOwner': 'Owner',
    'users.roleAdmin': 'Administrator',
    'users.roleModerator': 'Moderator',
    'users.lastActive': 'Last Active',
    'users.createdAt': 'Created',
    'users.status': 'Status',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.deleteConfirm': 'Are you sure you want to delete this user? This action cannot be undone.',
    
    // Permissions
    'permissions.viewDashboard': 'View Dashboard',
    'permissions.viewCases': 'View Cases',
    'permissions.createCase': 'Create Cases',
    'permissions.editCase': 'Edit Cases',
    'permissions.deleteCase': 'Delete Cases',
    'permissions.viewPrizes': 'View Prizes',
    'permissions.createPrize': 'Create Prizes',
    'permissions.editPrize': 'Edit Prizes',
    'permissions.deletePrize': 'Delete Prizes',
    'permissions.viewClaims': 'View Claims',
    'permissions.manageClaims': 'Manage Claims',
    'permissions.viewUsers': 'View Users',
    'permissions.manageUsers': 'Manage Users',
    'permissions.viewLogs': 'View Logs',
    'permissions.viewSettings': 'View Settings',
    'permissions.manageSettings': 'Manage Settings',

    // User Profile Modal
    'userModal.title': 'Lietotāja profils',
    'userModal.info': 'Informācija',
    'userModal.nickname': 'Segvārds',
    'userModal.phone': 'Tālrunis',
    'userModal.uuid': 'UUID',
    'userModal.joined': 'Dalībnieks kopš',
    'userModal.history': 'Atvēršanas vēsture',
    'userModal.inventory': 'Lietotāja inventārs',
    'userModal.item': 'Priekšmets',
    'userModal.case': 'Kaste',
    'userModal.date': 'Datums',
    'userModal.status': 'Statuss',
    'userModal.markDelivered': 'Atzīmēt kā piegādātu',
    'userModal.retryDelivery': 'Mēģināt piegādāt vēlreiz',
    'userModal.returnStock': 'Atgriezt noliktavā',
    'userModal.close': 'Aizvērt',

    // Logs
    'logs.title': 'Activity Logs',
    'logs.clientActivity': 'Client Activity',
    'logs.adminActivity': 'Admin Activity',
    'logs.player': 'Player',
    'logs.case': 'Case',
    'logs.prize': 'Prize',
    'logs.rarity': 'Rarity',
    'logs.value': 'Value',
    'logs.timestamp': 'Time',
    'logs.admin': 'Admin',
    'logs.action': 'Action',
    'logs.target': 'Target',
    'logs.details': 'Details',
    'logs.ipAddress': 'IP Address',
    'logs.sortBy': 'Sort by',
    'logs.sortOrder': 'Order',
    'logs.ascending': 'Ascending',
    'logs.descending': 'Descending',
    'logs.sortByDate': 'Date',
    'logs.sortByValue': 'Value',
    'logs.sortByRarity': 'Rarity',
    'logs.sortByPrize': 'Prize',
    'logs.sortByAction': 'Action',
    'logs.sortByAdmin': 'Admin',
    'logs.filterByRarity': 'Filter by Rarity',
    'logs.filterByAction': 'Filter by Action',
    'logs.allRarities': 'All Rarities',
    'logs.allActions': 'All Actions',
    
    // Admin Actions
    'actions.login': 'Login',
    'actions.logout': 'Logout',
    'actions.caseCreated': 'Created Case',
    'actions.caseEdited': 'Edited Case',
    'actions.caseDeleted': 'Deleted Case',
    'actions.prizeCreated': 'Created Prize',
    'actions.prizeEdited': 'Edited Prize',
    'actions.prizeDeleted': 'Deleted Prize',
    'actions.claimApproved': 'Approved Claim',
    'actions.claimRejected': 'Rejected Claim',
    'actions.claimPending': 'Marked Claim as Pending',
    'actions.userCreated': 'Created User',
    'actions.userEdited': 'Edited User',
    'actions.userDeleted': 'Deleted User',
    'actions.settingsChanged': 'Changed Settings',

    // Settings
    'settings.title': 'Settings',
    'settings.save': 'Save Changes',
    'settings.general': 'General Settings',
    'settings.appearance': 'Appearance Settings',
    'settings.siteLogo': 'Site Logo URL',
    'settings.siteLogoHint': 'URL of the logo displayed in the application',
    'settings.bannerBackground': 'Event Banner Background',
    'settings.bannerBackgroundHint': 'Background image for seasonal/event banner section',
    'settings.profileBackground': 'Profile Background',
    'settings.profileBackgroundHint': 'Background image for player profile header',
    'settings.snowEffect': 'Snow Effect',
    'settings.snowEffectHint': 'Enable or disable falling snow animation on the site',
    'settings.maintenanceMode': 'Maintenance Mode',
    'settings.maintenanceModeHint': 'Block all users from accessing the application during maintenance',
    'settings.enabled': 'Enabled',
    'settings.disabled': 'Disabled',
    'settings.lowStockThreshold': 'Low Stock Threshold',
    'settings.expireTtl': 'Prize Expiration (Hours)',
    'settings.rarities': 'Rarity Settings',
    'settings.presets': 'Rarity Presets',

    // Common
    'common.save': 'Saglabāt',
    'common.cancel': 'Atcelt',
    'common.delete': 'Dzēst',
    'common.edit': 'Rediģēt',
    'common.view': 'Skatīt',
    'common.close': 'Aizvērt',
    'common.confirm': 'Apstiprināt',
    'common.success': 'Veiksmīgi',
    'common.error': 'Kļūda',
    'common.loading': 'Ielādē...',
    'common.noData': 'Nav datu',
    'common.actions': 'Darbības',
  },
};

export function AdminLanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<AdminLanguage>(() => {
    const saved = localStorage.getItem('adminLanguage');
    return (saved as AdminLanguage) || 'en';
  });

  const handleSetLanguage = (lang: AdminLanguage) => {
    setLanguage(lang);
    localStorage.setItem('adminLanguage', lang);
  };

  const t = (key: string): string => {
    return adminTranslations[language][key] || adminTranslations['en'][key] || key;
  };

  return (
    <AdminLanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </AdminLanguageContext.Provider>
  );
}

export function useAdminLanguage() {
  const context = useContext(AdminLanguageContext);
  if (!context) {
    throw new Error('useAdminLanguage must be used within AdminLanguageProvider');
  }
  return context;
}